### ISSUE TITLE
export * from "./base-types"; SyntaxError: Unexpected token 'export' 

### ISSUE THREAD

**Issue by RyugaRyuzaki** [ThatOpen/engine_fragment#11]
### Describe the bug 📝

I'm using bim-fragment in Nodejs, it throw error

### Reproduction ▶️

https://github.com/RyugaRyuzaki/bim-fragment-server.git

### Steps to reproduce 🔢

1. Run "npm install"
2. Run "npm run dev"

### System Info 💻

```shell
Nodejs 20.0.5
```

### Used Package Manager 📦

npm

### Validations ✅

- [X] Read the [docs](https://ifcjs.github.io/info/docs/Introduction).
- [X] Check that there isn't [already an issue](https://github.com/IFCjs/fragment/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a IFC.js fragment issue and not a framework-specific issue. For example, if it's a THREE.js related bug, it should likely be reported to [mrdoob/threejs](https://github.com/mrdoob/three.js) instead.
- [X] Check that this is a concrete bug. For Q&A join our [Discord Chat Server](https://discord.gg/FXfyR4XrKT).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by nextdesusu** [comment]
You can fix this by using bundler for your backend app i ve solved this issue by using vite.

**Comment by agviegas** [comment]
I think this is already solved, as we are bundling our libraries. Let me know otherwise!
