### ISSUE TITLE
GeometryIds changed between 2.0.5 and 2.0.6

### ISSUE THREAD

**Issue by SimonSchneider** [ThatOpen/engine_fragment#37]
### Describe the bug 📝

I am upgrading from `2.0.4` to the latest version (`2.1.6`) and all my old fragment files have stopped working. The geometryIDs have changed. I've pinpointed that this commit introduced the regression.
https://github.com/ThatOpen/engine_fragment/commit/c53ac590ab69c5725b6ef4e124fa2e7660bf1741

I'm getting the error malformatted fragment because the fragment groups don't seem to contain geometryIDs that are stored in the streamedGeometries https://github.com/ThatOpen/engine_components/blob/23c99ee54aa30046e84bda902d45b171ceb504bf/packages/core/src/fragments/IfcGeometryTiler/src/base-types.ts#L4

My understanding was that fragment files should be persisted and should therefore be backwards compatible. Or will I have to regenerate all my fragment files?

### Steps to reproduce 🔢

* generate fragment files with 2.0.5
* upgrade lib on frontend to 2.0.7
* all the geometryIDs have changed and are no longer working.

### System Info 💻

```shell
System:
    OS: macOS 14.4.1
    CPU: (12) arm64 Apple M2 Max
    Memory: 72.89 MB / 64.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.19.1 - ~/.nvm/versions/node/v18.19.1/bin/node
    Yarn: 1.22.22 - ~/.nvm/versions/node/v18.19.1/bin/yarn
    npm: 10.2.4 - ~/.nvm/versions/node/v18.19.1/bin/npm
  Browsers:
    Chrome: 127.0.6533.89
    Safari: 17.4.1
```

### Used Package Manager 📦

yarn

### Validations ✅

- [X] Read the [docs](https://docs.thatopen.com/intro).
- [X] Check that there isn't [already an issue](https://github.com/ThatOpen/engine_components/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a repository issue and not a framework-specific issue. For example, if it's a THREE.js related bug, it should likely be reported to [mrdoob/threejs](https://github.com/mrdoob/three.js) instead.
- [X] Check that this is a concrete bug. For Q&A join our [Community](https://people.thatopen.com/).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by agviegas** [comment]
Hey @SimonSchneider that's weird 🤔 we use flatbuffers for file export/import, and it's not backwards compatible. That's why in [this commit](https://github.com/ThatOpen/engine_fragment/commit/c53ac590ab69c5725b6ef4e124fa2e7660bf1741) I introduced a multi-version serializer to allow backwards compatibility.

We'll take a look at this. In the meantime, I suggest you regenerate your fragments. We don't foresee any changes to the schema in a long time, so this should work.

**Comment by SimonSchneider** [comment]
thanks, I think the flatbuffer export was what broke for me. 
I've regenerated my fragments and the new ones work. I might have misjudged that this was the geometryIDs changing but in actuality it was just incompatible flatbuffers.

I'm unsure if you'll have to investigate this further as I'm quite sure it was the incompatible flatbuffers.
